[versions]
kotlin = "2.4.10"
ktlint-plugin = "14.2.0"
minecraft = "26.2"
paper = "26.2.build.80-beta"
commandapi = "12.0.0"

[libraries]
commandapi-paper-core = { module = "dev.jorel:commandapi-paper-core", version.ref = "commandapi" }
commandapi-kotlin-paper = { module = "dev.jorel:commandapi-kotlin-paper", version.ref = "commandapi" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.2.0" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version = "2.0.0-beta.21" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
