[versions]
kotlin = "2.3.21"
ktlint-plugin = "14.2.0"
minecraft = "26.1.2"
paper = "26.1.2.build.64-stable"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.2.0" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version = "2.0.0-beta.21" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
